# Generated by Django 5.2.5 on 2025-08-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('show_time', models.TimeField()),
                ('total_seats', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('poster_img', models.ImageField(upload_to='posters/')),
                ('rating', models.FloatField()),
                ('location', models.CharField(max_length=100)),
                ('theatres', models.ManyToManyField(related_name='movies_playing', to='booking.theatre')),
            ],
        ),
    ]
