# Generated by Django 5.2.5 on 2025-08-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='runtime_minutes',
            field=models.PositiveIntegerField(default=120),
        ),
    ]
