# Generated by Django 5.2.5 on 2025-08-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_movie_runtime_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='location',
        ),
        migrations.AddField(
            model_name='movie',
            name='locations',
            field=models.ManyToManyField(related_name='movies', to='booking.location'),
        ),
    ]
