# Generated by Django 5.2.5 on 2025-08-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_location_remove_movie_location_movie_locations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': 'Locations'},
        ),
        migrations.RemoveField(
            model_name='movie',
            name='theatres',
        ),
        migrations.RemoveField(
            model_name='theatre',
            name='location',
        ),
        migrations.AddField(
            model_name='theatre',
            name='locations',
            field=models.ManyToManyField(related_name='theatres', to='booking.location'),
        ),
        migrations.AddField(
            model_name='theatre',
            name='movies',
            field=models.ManyToManyField(related_name='theatres', to='booking.movie'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime_minutes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='theatre',
            name='total_seats',
            field=models.IntegerField(),
        ),
    ]
